HOSTNAME = "rails-tutorial"
Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-6"
    config.vm.network "private_network", id: "default-network", type: "dhcp", ip: "192.168.33.0"

    config.vm.provision :shell, :inline => <<-EOT

        #
        # iptables
        #
        service iptables stop
        chkconfig iptables off

        #
        # packages
        #
        yum install -y git gcc gcc-c++ openssl-devel readline-devel

        #
        # nginx
        #
        rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
        yum install -y nginx

        #
        # rbenv
        #
        git clone git://github.com/sstephenson/rbenv.git /usr/local/src/rbenv
        git clone git://github.com/sstephenson/ruby-build.git /usr/local/src/rbenv/plugins/ruby-build
        echo 'export RBENV_ROOT="/usr/local/src/rbenv"' >> /etc/profile.d/rbenv.sh
        echo 'export PATH="${RBENV_ROOT}/bin:${PATH}"' >> /etc/profile.d/rbenv.sh
        echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
        source /etc/profile.d/rbenv.sh

        #
        # ruby
        #
        rbenv install 2.4.3
        rbenv global 2.4.3

    EOT
end
