HOSTNAME = "rails-tutorial"
# APPLICATION = "hello_app"
APPLICATION = "toy_app"

Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-6"
    config.vm.network "private_network", ip: "192.168.33.15"

    config.vm.synced_folder "../5.1.4", "/var/www", \
        create: true, owner: 'vagrant', group: 'vagrant', \
        mount_options: ['dmode=775,fmode=644']

    config.vm.provider :virtualbox do |vb|
        if HOSTNAME != ""
            vb.name = HOSTNAME
        end
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        # vb.gui = true
    end

    config.vm.hostname = HOSTNAME

    if Vagrant.has_plugin?("vagrant-hostmanager")
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
    end

    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end

    config.vm.provision :shell, inline: <<-EOT

        #
        # iptables
        #
        service iptables stop
        chkconfig iptables off

        #
        # packages
        #
        yum install -y git gcc gcc-c++ openssl-devel readline-devel sqlite-devel

        #
        # nginx
        #
        rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
        yum install -y nginx
        cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.org
        cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.org
        cp /vagrant/conf/nginx/nginx.conf /etc/nginx/nginx.conf
        cp /vagrant/conf/nginx/hello_app.conf /etc/nginx/conf.d/hello_app.conf
        cp /vagrant/conf/nginx/toy_app.conf /etc/nginx/conf.d/toy_app.conf

        #
        # rbenv
        #
        git clone git://github.com/sstephenson/rbenv.git /usr/local/src/rbenv
        git clone git://github.com/sstephenson/ruby-build.git /usr/local/src/rbenv/plugins/ruby-build
        echo 'export RBENV_ROOT="/usr/local/src/rbenv"' >> /etc/profile.d/rbenv.sh
        echo 'export PATH="${RBENV_ROOT}/bin:${PATH}"' >> /etc/profile.d/rbenv.sh
        echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
        source /etc/profile.d/rbenv.sh

        #
        # ruby
        #
        rbenv install 2.4.3
        rbenv global 2.4.3

        #
        # bundler
        #
        rbenv exec gem install bundler

        #
        # rails
        #
        gem install rails -v 5.1.4
        cd /var/www/hello_app
        bundle install
        cd /var/www/toy_app
        bundle install

        #
        # migrate
        #
        cd /var/www/toy_app
        rails db:migrate
    EOT

    if APPLICATION == "hello_app"
        config.vm.provision :shell, run: "always", inline: <<-EOT
            #
            # change config
            #
            find /etc/nginx/conf.d/hello_app.conf.org -type f -exec mv {} /etc/nginx/conf.d/hello_app.conf \\;
            find /etc/nginx/conf.d/toy_app.conf -type f -exec mv {} /etc/nginx/conf.d/toy_app.conf.org \\;
        EOT
    end

    if APPLICATION == "toy_app"
        config.vm.provision :shell, run: "always", inline: <<-EOT
            #
            # change config
            #
            find /etc/nginx/conf.d/toy_app.conf.org -type f -exec mv {} /etc/nginx/conf.d/toy_app.conf \\;
            find /etc/nginx/conf.d/hello_app.conf -type f -exec mv {} /etc/nginx/conf.d/hello_app.conf.org \\;
        EOT
    end

    config.vm.provision :shell, run: "always", inline: <<-EOT
        #
        # start server
        #
        service nginx start
    EOT
end
