HOSTNAME = "rails-tutorial"
Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-6"
    config.vm.network "private_network", id: "default-network", type: "dhcp", ip: "192.168.33.0"

    config.vm.provision :shell, :inline => <<-EOT

        #
        # iptables
        #
        service iptables stop
        chkconfig iptables off

        #
        # packages
        #
        yum install -y git gcc gcc-c++ openssl-devel readline-devel

        #
        # nginx
        #
        rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
        yum install -y nginx

        #
        # rbenv
        #
        git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
        git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
        echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile

    EOT
end
